## 머신러닝 분석과정 예시- 분류분석


In [15]:
from sklearn.datasets import load_iris
import pandas as pd

In [16]:
iris = load_iris()
iris_dt = iris.data
iris_label = iris.target

df = pd.DataFrame(data = iris_dt, columns = iris.feature_names)
df['label'] = iris_label

In [18]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [20]:
df['label'].unique()

array([0, 1, 2])

In [21]:
df.shape

(150, 5)

## iris는 모든 독립변수가 연속형이고 단위가 동일하기에 표준화 또는 정규화가 필요없다. 또한 결측치가 없다

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris_dt, iris_label, test_size = 0.2, random_state = 0, stratify = iris_label)

In [23]:
df.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
label                0
dtype: int64

In [24]:
from sklearn.tree import DecisionTreeClassifier
dtree_clf_5 = DecisionTreeClassifier(max_depth = 5, random_state = 100)
dtree_clf_3 = DecisionTreeClassifier(max_depth = 3, random_state = 100)
dtree_clf_1 = DecisionTreeClassifier(max_depth = 1, random_state = 100)

In [26]:
from sklearn.model_selection import cross_val_score
import numpy as np
scores = cross_val_score(dtree_clf_5, x_train,y_train,scoring = 'accuracy',cv = 10) #내부적으로 fit을 하기 때문에 따로 하지 않아도 된다.
#간단히 성능평가 하기 좋은듯?
print(np.round(scores,3))
print(np.round(np.mean(scores),4))

[0.917 1.    0.917 1.    1.    0.833 1.    0.917 1.    0.833]
0.9417


In [27]:
from sklearn.model_selection import cross_val_score
import numpy as np
scores = cross_val_score(dtree_clf_3, x_train,y_train,scoring = 'accuracy',cv = 10) #내부적으로 fit을 하기 때문에 따로 하지 않아도 된다.
#간단히 성능평가 하기 좋은듯?
print(np.round(scores,3))
print(np.round(np.mean(scores),4))

[0.917 1.    0.917 0.917 1.    0.833 1.    0.917 0.917 0.833]
0.925


In [28]:
from sklearn.model_selection import cross_val_score
import numpy as np
scores = cross_val_score(dtree_clf_1, x_train,y_train,scoring = 'accuracy',cv = 10) #내부적으로 fit을 하기 때문에 따로 하지 않아도 된다.
#간단히 성능평가 하기 좋은듯?
print(np.round(scores,3))
print(np.round(np.mean(scores),4))

[0.667 0.667 0.667 0.667 0.667 0.667 0.667 0.667 0.667 0.667]
0.6667


In [30]:
dtree_clf_5.fit(x_train, y_train)
pred = dtree_clf_5.predict(x_test)
from sklearn.metrics import accuracy_score
print("의사결정나무 정확도 :", accuracy_score(y_test, pred))

의사결정나무 정확도 : 0.9666666666666667


In [32]:
pred_df = pd.DataFrame(pred, columns = ['pred Species'])

In [33]:
pred_df.head()

pred Species
0             0
1             1
2             0
3             2
4             0

In [34]:
actual = pd.DataFrame(y_test, columns=['actual Species'])
actual.head()

actual Species
0               0
1               1
2               0
3               2
4               0